# Generated by Django 2.1.3 on 2019-05-21 00:10

from django.db import migrations, models
import marketing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupon', models.CharField(max_length=100)),
                ('percentage', models.CharField(blank=True, max_length=20, null=True, validators=[marketing.models.valid_percentage])),
                ('hard_discount', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='used_cupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupon', models.CharField(max_length=100, null=True)),
                ('user', models.CharField(max_length=100, null=True)),
                ('order', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
