# Generated by Django 2.2.1 on 2019-06-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupons',
            name='free_shipping',
            field=models.BooleanField(default=True),
        ),
    ]
