# Generated by Django 2.2.1 on 2019-07-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_cupons_free_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupons',
            name='free_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
