# Generated by Django 2.2.1 on 2019-09-02 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20190715_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='used_cupons',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
    ]
