# Generated by Django 2.1.3 on 2019-05-06 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplesPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('5cm x 5cm', '5 cm x 5 cm'), ('7cm x 7cm', '7 cm x 7 cm'), ('10cm x 10cm', '10 cm x 10 cm'), ('13cm x 13cm', '13 cm x 13 cm')], max_length=20)),
                ('quantity', models.CharField(choices=[('50', '50'), ('100', '100'), ('200', '200'), ('300', '300'), ('500', '500'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('5000', '5000'), ('10000', '10000')], max_length=20)),
                ('price', models.IntegerField(default=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='costo_de_los_productos',
            new_name='ProductsPricing',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='shipping_address2',
            new_name='reference',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='stock',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
        migrations.AlterField(
            model_name='sample',
            name='image',
            field=models.ImageField(blank=True, upload_to='sample_images'),
        ),
        migrations.AddField(
            model_name='samplespricing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category'),
        ),
        migrations.AddField(
            model_name='samplespricing',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Sample'),
        ),
    ]
