# Generated by Django 2.1.3 on 2019-05-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190506_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default=12, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='sku',
            field=models.CharField(default=12, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
