# Generated by Django 2.2.1 on 2019-09-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_pack_packspricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='price',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='pack',
            name='quantity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
