# Generated by Django 2.2.1 on 2019-09-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190917_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='subcategory',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
