# Generated by Django 2.2.1 on 2019-09-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_pack_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PacksPricing',
        ),
    ]
