# Generated by Django 2.2.1 on 2019-10-04 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190928_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitaryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('sku', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('subcategory1', models.CharField(blank=True, max_length=20, null=True)),
                ('subcategory2', models.CharField(blank=True, max_length=20, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.IntegerField(default=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='unitaryproducts')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
            options={
                'verbose_name': 'unitary product',
                'verbose_name_plural': 'unitary products',
                'ordering': ('name',),
            },
        ),
    ]
