# Generated by Django 2.2.1 on 2019-10-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_unitaryproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitaryproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=4),
        ),
    ]
