# Generated by Django 2.2.1 on 2019-10-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20191004_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitaryproduct',
            name='quantity',
            field=models.CharField(blank=True, default=1, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unitaryproduct',
            name='sku',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
