# Generated by Django 2.2.1 on 2023-08-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20191011_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitaryproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=4),
        ),
    ]
