# Generated by Django 2.1.3 on 2019-05-18 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Cart',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('5cm x 5cm', '5 cm x 5 cm'), ('7cm x 7cm', '7 cm x 7 cm'), ('10cm x 10cm', '10 cm x 10 cm'), ('13cm x 13cm', '13 cm x 13 cm')], max_length=20)),
                ('quantity', models.CharField(choices=[('50', '50'), ('100', '100'), ('200', '200'), ('300', '300'), ('500', '500'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('5000', '5000'), ('10000', '10000')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='files')),
                ('comment', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('step_two_complete', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SampleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('5cm x 5cm', '5 cm x 5 cm'), ('7cm x 7cm', '7 cm x 7 cm'), ('10cm x 10cm', '10 cm x 10 cm'), ('13cm x 13cm', '13 cm x 13 cm')], max_length=20)),
                ('quantity', models.CharField(choices=[('50', '50'), ('100', '100'), ('200', '200'), ('300', '300'), ('500', '500'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('5000', '5000'), ('10000', '10000')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='files')),
                ('comment', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('step_two_complete', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Sample')),
            ],
        ),
    ]
