# Generated by Django 2.1.3 on 2019-01-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
