# Generated by Django 2.2.1 on 2019-07-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20190617_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='file',
            new_name='file_a',
        ),
        migrations.RenameField(
            model_name='sampleitem',
            old_name='file',
            new_name='file_a',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='file_b',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='sampleitem',
            name='file_b',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
