# Generated by Django 2.1.3 on 2019-01-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20190117_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
