# Generated by Django 2.2.1 on 2019-08-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20190826_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleitem',
            old_name='file_a',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='sampleitem',
            name='file_b',
        ),
    ]
