# Generated by Django 2.2.1 on 2019-09-17 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_pack_packspricing'),
        ('cart', '0008_auto_20190831_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('varios', 'varios'), ('3cm x 3cm', '3 cm x 3 cm'), ('5cm x 5cm', '5 cm x 5 cm'), ('7cm x 7cm', '7 cm x 7 cm'), ('10cm x 10cm', '10 cm x 10 cm'), ('13cm x 13cm', '13 cm x 13 cm')], max_length=20)),
                ('quantity', models.CharField(choices=[('10', '10'), ('20', '20'), ('50', '50'), ('100', '100'), ('200', '200'), ('300', '300'), ('500', '500'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('5000', '5000'), ('10000', '10000')], max_length=20)),
                ('file_a', models.FileField(blank=True, null=True, upload_to='files')),
                ('file_b', models.FileField(blank=True, null=True, upload_to='files')),
                ('comment', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('step_two_complete', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Pack')),
            ],
        ),
    ]
