# Generated by Django 2.2.1 on 2019-10-04 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_unitaryproduct'),
        ('cart', '0011_auto_20190928_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitaryProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.CharField(blank=True, max_length=20, null=True)),
                ('file_a', models.FileField(blank=True, null=True, upload_to='files')),
                ('file_b', models.FileField(blank=True, null=True, upload_to='files')),
                ('comment', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('step_two_complete', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Pack')),
            ],
        ),
    ]
