# Generated by Django 2.2.1 on 2019-09-03 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_cupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cupon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.Cupons'),
        ),
    ]
