# Generated by Django 2.2.1 on 2019-09-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190902_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stickers_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
