# Generated by Django 2.2.1 on 2019-09-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('recibido_pagado', 'Recibido y pagado'), ('recibido_no_pagado', 'Recibido pero no pagado'), ('en_proceso', 'En proceso'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='recibido_pagado', max_length=20),
        ),
    ]
