# Generated by Django 2.2.1 on 2019-10-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190927_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('recibido_pagado', 'Recibido y pagado'), ('recibido_no_pagado', 'Recibido pero no pagado'), ('en_proceso', 'En proceso'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado por no pagar')], default='recibido_pagado', max_length=20),
        ),
    ]
