# Generated by Django 2.2.1 on 2023-08-14 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20191004_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Order Summary',
                'verbose_name_plural': 'Orders Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.order',),
        ),
    ]
